### ISSUE TITLE
Error when searching for "col 70"

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/elite-investigations#7]
IEx session:

```
iex> Elite.search_stories("col 70")
[debug] QUERY ERROR source="stories" db=5.6ms queue=0.8ms
SELECT s0."id", s0."body", s0."date", s0."image", s0."nid", s0."slug", s0."title", s0."inserted_at", s0."updated_at" FROM "stories"AS s0 INNER JOIN (SELECT s0."nid" AS "s_nid", s0."title" AS "s_title", setweight(to_tsvector(s0."title"), 'A') || setweight(to_tsvector(s0."body"), 'B') AS "document" FROM "stories" AS s0) AS s1 ON s1."s_nid" = s0."nid" WHERE (s1."document" @@ to_tsquery($1)) ORDER BY ts_rank(s1."document", to_tsquery($2)) DESC ["col 70", "col 70"]
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error in tsquery: "col 70"
    (ecto_sql) lib/ecto/adapters/sql.ex:624: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:557: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
```

**Comment by lee-dohm** [comment]
It appears that [`to_tsquery` requires that all tokens be separated by query operators](https://www.postgresql.org/docs/11/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES) such as `&`, `|`, and `<->`:

> to_tsquery creates a tsquery value from querytext, which must consist of single tokens separated by the tsquery operators & (AND), | (OR), ! (NOT), and <-> (FOLLOWED BY), possibly grouped using parentheses.

It looks like using `web search_to_tsquery` will be much more forgiving.
